# Generated by Django 4.1 on 2022-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_disease_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
