# Generated by Django 4.1 on 2022-09-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_symptom_alter_disease_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='symptom',
            new_name='body',
        ),
    ]
